### ISSUE TITLE
Weight from no .cnr / CNVkit files, laggy html files, query fields and cytobands

### ISSUE THREAD

**Issue by Tintest** [rghu/reconCNV#2]
Hello,

I am writing to you by email about your reconCNV tool. First, I would like to thank you for developing it. 

Unfortunately, to use it, I'm “hijacking” its way of functioning, so I don't know if you will be able to help me. I do CNV calling on germline exomes (capture) with GATK4. So, these are not normal / tumor paired data, but data from an index case against a learning model built with presumably healthy patients, which in my opinion is quite close conceptually. 

Problem: GATK4 does not output .cnr or .cns files, I had to convert and transform the data. For the chromosome, start, end, gene and depth fields, no worries. For log2, the output ratios by GATK4 are in base 10, so I applied a Log2FC function and the transformed ratios seemed adapted (centered on 0, even if there are some outliers). 

The first problem comes from the weight which is not calculated by GATK4. I tried to calculate it from Log2FC roughly in the way indicated  [here](https://www.biostars.org/p/379475/) by the developer of CNVkit on my entire cohort. But it didn't give the expected results. I thought I would try to calculate a z-score per patient per interval as a weight instead. It gave me better results, but still not enough. 

So I have several questions / requests for you : 

Is there a way to correctly produce weight data from other tools than CNV kit ?

Also, I have a lot of freeze / crash in the .html produced by reconCNV, but I guess this might be because it is not optimized for the capture data as shown on your github? 

Is there a way to add the support of cytobands .bed file to your tool ?

Is there a way to add a query gene field to directly highlight or zoom on a specific gene ? Or a query field for coordinates ?

[Here ](https://filesender.renater.fr/?s=download&token=4305c1bc-5d7f-4991-8a39-6d5d02f2ce42) is an example of a ratio file produced by GATK4 and an exemple .cnr file with z-score as weight. 

Regards.

**Comment by rghu** [comment]
Hey @Tintest,

Thanks for checking out our visualization tool!

reconCNV handles visualization of germline/somatic CNV data agnostically, so it should be able to help you visualize results from GATK4. The changes that you need to make will be to remove the reference sequence header tags - contig lengths - on the GATK4 TSV file (as reconCNV does not expect it) and provide the column titles to the configuration file (as shown below). 

```
"files":{
                "genome_build": "hg19",
                "ratio_file":{
                        "column_names":{
                                "chromosome": "CONTIG",
                                "start":"START",
                                "end":"END",
                                "gene": "gene",
                                "log2FC": "LINEAR_COPY_RATIO",
                                "weight": "weight"
                        },
```

There is no need to transform the data from GATK4 since log2FC displayed in the output is only for aesthetics. You can plot your log10 ratios directly and accordingly change the y-axis label in the configuration file.

```
"y_axis_label": "log10(FC)"
```

Weight is not a mandatory field and if reconCNV cannot find the field in the delimited file it defaults to uniformly weighting all data points. Note: weight alters the size of each data points plotted. If you find the data points are plotted too small or too big you can change the weight scaling factor in the configuration file.

```
"weight_scaling_factor": 40
```

The lag issue might be because of the hover tool tip (that displays the metadata). The performance should be much faster if you toggle it off before browsing the data. The capture panel we use is smaller than an exome so we have it active by default but with the exome there are many more data points that overwhelms the browser. In the next version of the tool we can make the default behavior of the hover tool available to the user via the configuration file.

You can use the annotation track to display the cytoband information. See https://github.com/rghu/reconCNV#annotation-plot

If a gene summary file is provided reconCNV will generate a multioption list (https://github.com/rghu/reconCNV#tables) to highlight genes of interest. At this point there is no functionality to query coordinates.

**Comment by Tintest** [comment]
Hello,

Thank you for your answer, it solved a lot of my questions. My results are not in log10 but only in base10. I kept the log2FC for now, it's not a problem.

Regarding the cytobands, I already had a gene annotation track, but I'm talking about the display of chromosomal cytobands, like the [karyoploteR package](https://bernatgel.github.io/karyoploter_tutorial//Examples/MultipleDataTypes/MultipleDataTypes.html) for example. I know it's quite complicated to do, but it's something that molecular biologists are asking for. In my opinion, it could be an important added value for your tool.

I would like to ask you one last question, I tried to integrate _.vcf_ files generated with GATK HaplotypeCaller to have VAF in my plots, but it didn't work. I tried with a _.vcf_ file, a _.g.vcf_ file and a genotyped _.g.vcf_ file. I noticed that you were using _.vcf_ files produced with FreeBayes, would it be possible to make your tool compatible with HaplotypeCaller? 

[Here ](https://filesender.renater.fr/?s=download&token=74c26e27-3a25-44c2-9643-7ec40fbdb605) are some examples files.

Here are the errors : 

- 99-NIST002-2_S1.vcf : ._vcf_ file 

```
Traceback (most recent call last):
  File "reconCNV/reconCNV.py", line 372, in <module>
    ((record.INFO[config['files']['vcf_file']['info_fields']['forward_alt_reads']][0] +
KeyError: 'SAF'
```

- 99-NIST002-2_S1_HC.g.vcf : _.g.vcf file_

```
Traceback (most recent call last):
  File "reconCNV/reconCNV.py", line 366, in <module>
    if record.INFO[config['files']['vcf_file']['info_fields']['depth']] >= \
KeyError: 'DP'
```

- 99-NIST002-2_S1_genotyped.vcf : genotyped _g.vcf_ file

```
Traceback (most recent call last):
  File "/home/tintest/.local/lib/python3.6/site-packages/vcf/parser.py", line 390, in _parse_info
    val = self._map(int, vals)
  File "/home/tintest/.local/lib/python3.6/site-packages/vcf/parser.py", line 360, in _map
    for x in iterable]
  File "/home/tintest/.local/lib/python3.6/site-packages/vcf/parser.py", line 360, in <listcomp>
    for x in iterable]
ValueError: invalid literal for int() with base 10: '1/1:7|0/0:330|0/1:4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "reconCNV/reconCNV.py", line 365, in <module>
    for record in vcf_reader:
  File "/home/tintest/.local/lib/python3.6/site-packages/vcf/parser.py", line 572, in __next__
    info = self._parse_info(row[7])
  File "/home/tintest/.local/lib/python3.6/site-packages/vcf/parser.py", line 394, in _parse_info
    val = self._map(float, vals)
  File "/home/tintest/.local/lib/python3.6/site-packages/vcf/parser.py", line 360, in _map
    for x in iterable]
  File "/home/tintest/.local/lib/python3.6/site-packages/vcf/parser.py", line 360, in <listcomp>
    for x in iterable]
ValueError: could not convert string to float: '1/1:7|0/0:330|0/1:4'
```

Some fields are therefore absent from GATK or incompatible with your integration of .vcf files, which is surely modelled on FreeBayes .vcf files.

Regards.

**Comment by rghu** [comment]
For some reason I am not able to access the files through the link, but you can modify the the configuration file to point to the info fields specified by HaplotypeCaller. (Requires total depth, forward allele depth and reverse allele depth - let me know if HC doesn't produce these three fields) You are correct the default info fields in the example configuration file is based on Freebayes.

Thanks for the tip on displaying karyoploteR like visualization of cytoband information. We will add it to our list of future updates.

**Comment by Tintest** [comment]
Hello,

To follow up your message, I send you back a[ g.vcf file via another website](https://mega.nz/file/Y5tWiJ5b#siqDfzt9v7fNT6eq81H8JPfi9fZQidWgNpksuNyABV4). Indeed, it is the only file which, for non-reference variants, summarizes the information of the number of reads on the forward and reverse strand. This information is reported by the field ```AS_SB_TABLE```

 ```##INFO=<ID=AS_SB_TABLE,Number=1,Type=String,Description="Allele-specific forward/reverse read counts for strand bias tests">```

Unfortunately the formatting being different from Freebayes, I think it will take some action on your part to support GATK HaplotypeCaller.

Also note that the definition of the _DP_ in HaplotypeCaller is not exactly the same as in FreeBayes.

```##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth (reads with MQ=255 or with bad mates are filtered)">```

However, I doubt it would make any difference. 

Regards.
